# name: Publish
# on:
#   push:
#     branches:
#       - master

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - uses: actions/checkout@v4

#       - name: cd the packages file
#         run: cd packages/jsr-utils

#       - name: Publish package
#         run: npx jsr publish